# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lkecli < Formula
  desc "LKE Helper CLI"
  homepage ""
  version "0.0.1"

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Darwin_x86_64.tar.gz"
      sha256 "ba9905cfdf22e089903b8a291299f42a4a4be01810182e71cd74ea981f5b1e13"

      def install
        bin.install "lkecli"
      end
    end
    on_arm do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Darwin_arm64.tar.gz"
      sha256 "2141824ca37a7f170e646fa8c22b0f0497a8f82a77b8d815990bd4b31ea22319"

      def install
        bin.install "lkecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Linux_x86_64.tar.gz"
        sha256 "c019f9cd121111efba72762796ec06274fad06cc73ab8aa3cb77d4256c941d97"

        def install
          bin.install "lkecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Linux_arm64.tar.gz"
        sha256 "f0501d1eae124d6b77865586417fec9083684c70f49cfce81bd35a9157ece625"

        def install
          bin.install "lkecli"
        end
      end
    end
  end
end
