# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lkecli < Formula
  desc "LKE Helper CLI"
  homepage ""
  version "0.0.2-beta.3"

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.2-beta.3/lkecli_Darwin_x86_64.tar.gz"
      sha256 "0e50eb854e166b139bb6b30fd443f5c04a831e1a7c0270e9f2ff85acf2f8c854"

      def install
        bin.install "lkecli"
      end
    end
    on_arm do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.2-beta.3/lkecli_Darwin_arm64.tar.gz"
      sha256 "c068e333d6cc56c99ec2fff64aa778b812b2c8bbc130898c598741edf149a7e3"

      def install
        bin.install "lkecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.2-beta.3/lkecli_Linux_x86_64.tar.gz"
        sha256 "138bff01bbc1edbddaad9716df0ada8ffa949e845e53b356fb50ff119d2415e7"

        def install
          bin.install "lkecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.2-beta.3/lkecli_Linux_arm64.tar.gz"
        sha256 "b44b5139999b5c8b3214d3116349eb330eb5c13795e8ce35e30eb98439713e98"

        def install
          bin.install "lkecli"
        end
      end
    end
  end
end
