# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lkecli < Formula
  desc "LKE Helper CLI"
  homepage ""
  version "0.0.1"

  depends_on "kubectl"

  on_macos do
    on_intel do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Darwin_x86_64.tar.gz"
      sha256 "75fd08c53bb824aa103eaf4848ebad50cae3cebeed0454c2ba1d08a51ba7c722"

      def install
        bin.install "lkecli"
      end
    end
    on_arm do
      url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Darwin_arm64.tar.gz"
      sha256 "e69aea3ae93c0d7f0d17b3e6a4704b90315ff2da5d35c8f34eb5071cd205735f"

      def install
        bin.install "lkecli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Linux_x86_64.tar.gz"
        sha256 "ee84c62b669cf83d1c193453a2996bd73a5af91efd3ba2cd325f44e88f3802b2"

        def install
          bin.install "lkecli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/endocrimes/lkecli/releases/download/v0.0.1/lkecli_Linux_arm64.tar.gz"
        sha256 "c130de549c610dbd52ea6da845126a6905fc302b20b230e2ec9730105cf50356"

        def install
          bin.install "lkecli"
        end
      end
    end
  end
end
